# Generated by Django 6.0 on 2025-12-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de Venda (R$)')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Estoque Disponível')),
                ('alerta_minimo', models.IntegerField(default=5, verbose_name='Alerta de Reposição')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.CharField(max_length=255, verbose_name='URL da Imagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem Principal?')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='estoque.produto', verbose_name='Produto Associado')),
            ],
        ),
    ]
