# Generated by Django 6.0 on 2025-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemproduto',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(default='', upload_to='produtos/', verbose_name='Arquivo de Imagem'),
            preserve_default=False,
        ),
    ]
