# Generated by Django 6.0 on 2025-12-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
    ]
