# Generated by Django 6.0 on 2026-01-04 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_fretebairro_alter_imagemproduto_imagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('pago', 'Pagamento Confirmado / Aguardando Envio'), ('enviado', 'Pedido Enviado'), ('entregue', 'Pedido Entregue'), ('cancelado', 'Pedido Cancelado')], default='pendente', max_length=20)),
                ('itens_json', models.TextField()),
                ('id_pagamento_mp', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
