# Generated by Django 6.0 on 2026-01-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, help_text='Ex: P, M, G ou 38, 40, 42', max_length=50, null=True, verbose_name='Tamanhos Disponíveis'),
        ),
    ]
