# Generated by Django 6.0 on 2026-01-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='tamanho',
            new_name='tamanhos_disponiveis',
        ),
    ]
