# Generated by Django 6.0 on 2026-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_rename_tamanho_produto_tamanhos_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='novidade',
            field=models.BooleanField(default=False, verbose_name='É novidade?'),
        ),
    ]
