# Generated by Django 6.0 on 2026-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_perfilusuario_complemento_produto_novidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Colocar em destaque na tela inicial?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhos_disponiveis',
            field=models.CharField(blank=True, help_text='Ex: P, M, G ou 38, 40, 42, Único', max_length=50, null=True, verbose_name='Tamanhos Disponíveis'),
        ),
    ]
