# Generated by Django 6.0 on 2026-01-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_produto_destaque_alter_produto_tamanhos_disponiveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Apenas para identificação', max_length=100)),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='icones_categorias/', verbose_name='Ícone da Categoria'),
        ),
        migrations.CreateModel(
            name='DestaqueLuxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Título (Ex: Vestido Elegante)')),
                ('imagem', models.ImageField(upload_to='luxo/', verbose_name='Foto do Card')),
                ('produto_associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Linkar Produto (Opcional)')),
            ],
        ),
    ]
