# Generated by Django 6.0 on 2026-01-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_banner_categoria_imagem_destaqueluxo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagem',
        ),
        migrations.AddField(
            model_name='secao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='icones_categorias/', verbose_name='Ícone da Categoria'),
        ),
    ]
