# Generated by Django 6.0 on 2026-01-05 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_remove_categoria_imagem_secao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaqueluxo',
            name='produto_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Se quiser que a vitrine direcione para um produto, selecione aqui produto desejado.'),
        ),
    ]
