# Generated by Django 6.0 on 2026-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_alter_destaqueluxo_produto_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cores_disponiveis',
            field=models.CharField(blank=True, help_text='Ex: Preto, Branco, Azul', max_length=50, null=True, verbose_name='Cores Disponíveis'),
        ),
    ]
