# Generated by Django 6.0 on 2026-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_produto_cores_disponiveis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='imagemproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('produto',), name='uma_imagem_principal_por_produto'),
        ),
    ]
